//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612018_1612175_PlaneTicketSelling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.LICHBAYs = new HashSet<LICHBAY>();
        }
    
        public int MaCB { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBay { get; set; }
        public string SBDi { get; set; }
        public string SBDen { get; set; }
        public Nullable<int> GheVip { get; set; }
        public Nullable<int> GheThuong { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHBAY> LICHBAYs { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
    }
}
