//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612018_1612175_PlaneTicketSelling.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaKH { get; set; }
        public int MaCB { get; set; }
        public System.DateTime NgayDi { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<int> SoVeVip { get; set; }
        public Nullable<int> SoVeThuong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsDatCho { get; set; }
    
        public virtual KHACH KHACH { get; set; }
        public virtual LICHBAY LICHBAY { get; set; }
    }
}
