//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612018_1612175_PlaneTicketSelling.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanVeMayBayEntities : DbContext
    {
        public QLBanVeMayBayEntities()
            : base("name=QLBanVeMayBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACH> KHACHs { get; set; }
        public virtual DbSet<LICHBAY> LICHBAYs { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<SBTRUNGGIAN> SBTRUNGGIANs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
